-- =====================================================
-- SCHEMA-ONLY DEPLOYMENT SCRIPT
-- =====================================================
-- Run this in your Supabase SQL Editor to create the
-- database structure without any seed data.
-- =====================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CORE TABLES

CREATE TABLE IF NOT EXISTS product_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text UNIQUE NOT NULL,
    description text
);

CREATE TABLE IF NOT EXISTS bulb_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    code text UNIQUE NOT NULL, -- e.g. H4, H7
    description text
);

CREATE TABLE IF NOT EXISTS bulb_type_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    base_name text NOT NULL, -- e.g. "LED Headlight Kit"
    variant_name text NOT NULL, -- e.g. "H4/H7/9005"
    display_name text NOT NULL,
    compatibility_list text[],
    description text,
    is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    contact_person text,
    email text,
    phone text,
    address text
);

CREATE TABLE IF NOT EXISTS store_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name text DEFAULT 'Ken''s Auto Parts',
    tax_rate numeric DEFAULT 0.12,
    low_stock_threshold integer DEFAULT 5,
    currency text DEFAULT 'PHP',
    updated_at timestamp with time zone DEFAULT now()
);

-- 3. ADMINS TABLE (Authentication)

CREATE TABLE IF NOT EXISTS admins (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    full_name TEXT,
    role TEXT DEFAULT 'admin' CHECK (role IN ('super_admin', 'admin', 'manager', 'staff')),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. PRODUCTS & VARIANTS

CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    sku text UNIQUE,
    barcode text,
    brand text,
    category_id bigint REFERENCES product_categories(id),
    bulb_type_id bigint REFERENCES bulb_types(id),
    supplier_id bigint REFERENCES suppliers(id),
    selling_price numeric(10,2) DEFAULT 0,
    cost_price numeric(10,2) DEFAULT 0,
    stock_quantity integer DEFAULT 0,
    min_stock_level integer DEFAULT 5,
    reorder_level integer DEFAULT 10,
    description text,
    image_url text,
    voltage numeric,
    wattage numeric,
    color_temperature text, 
    lumens numeric,
    beam_type text,
    specifications jsonb DEFAULT '{}'::jsonb,
    has_variants boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS product_bulb_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    product_id bigint REFERENCES products(id) ON DELETE CASCADE,
    variant_id bigint REFERENCES bulb_type_variants(id) ON DELETE RESTRICT, -- Can be null for custom variants
    
    -- Specific Variant Data
    bulb_type text, -- Display type (e.g., H4, H11) stored directly
    color_temperature numeric(10,2), -- Supports range filtering
    variant_color text, -- Display string e.g. "Red", "6000K"
    variant_sku text,
    variant_barcode text,
    description text,
    
    -- Pricing & Inventory Specific to Variant
    selling_price numeric(10,2) DEFAULT 0,
    cost_price numeric(10,2) DEFAULT 0,
    stock_quantity integer DEFAULT 0,
    min_stock_level integer DEFAULT 5,
    price_adjustment numeric(10,2) DEFAULT 0, -- Legacy support
    
    is_primary boolean DEFAULT false,
    
    UNIQUE(product_id, variant_id, variant_color) 
);

-- 5. SALES & TRANSACTIONS

CREATE TABLE IF NOT EXISTS sales (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    items jsonb NOT NULL, -- Array of cart items
    subtotal numeric(10,2) NOT NULL,
    tax numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    payment_method text DEFAULT 'Cash',
    customer_name text,
    customer_email text,
    receipt_number text,
    transaction_status text DEFAULT 'completed',
    staff_id text,
    notes text
);

-- Ensure all necessary columns exist in product_bulb_variants (migration safety)
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS price_adjustment numeric(10,2) DEFAULT 0;
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS variant_color text;
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS bulb_type text;
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS selling_price numeric(10,2) DEFAULT 0;
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS cost_price numeric(10,2) DEFAULT 0;
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS min_stock_level integer DEFAULT 5;
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS variant_sku text;
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS variant_barcode text;
ALTER TABLE product_bulb_variants ADD COLUMN IF NOT EXISTS color_temperature numeric(10,2);

-- 6. VIEWS

DROP VIEW IF EXISTS pos_product_variants;
CREATE OR REPLACE VIEW pos_product_variants AS
SELECT 
    p.id as product_id,
    p.sku,
    p.name as base_name,
    p.brand,
    p.selling_price as base_price,
    
    pbv.id as id, -- Unique ID for POS and frontend keys
    pbv.id as variant_id, 
    COALESCE(btv.display_name, pbv.bulb_type) as display_name,
    btv.compatibility_list,
    COALESCE(pbv.description, btv.description) as variant_description,
    
    -- Price Logic
    CASE 
        WHEN pbv.selling_price > 0 THEN pbv.selling_price
        ELSE p.selling_price + COALESCE(pbv.price_adjustment, 0)
    END as final_price,
    
    pbv.stock_quantity,
    pbv.min_stock_level,
    pbv.is_primary,
    pbv.variant_sku,
    pc.name as category,
    p.image_url,
    
    -- Color Logic: Variant Color > Product Color
    COALESCE(pbv.variant_color, CAST(p.color_temperature AS text)) as color_temperature
    
FROM products p
JOIN product_bulb_variants pbv ON p.id = pbv.product_id
LEFT JOIN bulb_type_variants btv ON pbv.variant_id = btv.id
LEFT JOIN product_categories pc ON p.category_id = pc.id
WHERE p.has_variants = true
  AND (btv.is_active = true OR btv.id IS NULL) -- Allow active variants or custom ones (null variant_id)
ORDER BY p.name, display_name;

-- 7. FUNCTIONS & TRIGGERS

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE OR REPLACE FUNCTION sync_product_stock_from_variants()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE products
    SET stock_quantity = (
        SELECT COALESCE(SUM(stock_quantity), 0)
        FROM product_bulb_variants
        WHERE product_id = COALESCE(NEW.product_id, OLD.product_id)
    )
    WHERE id = COALESCE(NEW.product_id, OLD.product_id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply Triggers
DROP TRIGGER IF EXISTS trigger_sync_product_stock ON product_bulb_variants;
CREATE TRIGGER trigger_sync_product_stock
AFTER INSERT OR UPDATE OR DELETE ON product_bulb_variants
FOR EACH ROW EXECUTE FUNCTION sync_product_stock_from_variants();

DROP TRIGGER IF EXISTS update_admins_updated_at ON admins;
CREATE TRIGGER update_admins_updated_at BEFORE UPDATE ON admins 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_products_updated_at ON products;
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products 
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 8. SECURITY POLICIES (RLS)

-- Enable RLS on all tables
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE bulb_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE bulb_type_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_bulb_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- 9. DEFAULT POLICIES (Open Access for Demo/Development)

-- Public Read Policies
DROP POLICY IF EXISTS "Public Read Categories" ON product_categories;
CREATE POLICY "Public Read Categories" ON product_categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read BulbTypes" ON bulb_types;
CREATE POLICY "Public Read BulbTypes" ON bulb_types FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Variants" ON bulb_type_variants;
CREATE POLICY "Public Read Variants" ON bulb_type_variants FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Suppliers" ON suppliers;
CREATE POLICY "Public Read Suppliers" ON suppliers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Products" ON products;
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read ProductVariants" ON product_bulb_variants;
CREATE POLICY "Public Read ProductVariants" ON product_bulb_variants FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Settings" ON store_settings;
CREATE POLICY "Public Read Settings" ON store_settings FOR SELECT USING (true);

-- Public Write Policies (Safe to modify for stricter rules later)
DROP POLICY IF EXISTS "Public Write Products" ON products;
CREATE POLICY "Public Write Products" ON products FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Write ProductVariants" ON product_bulb_variants;
CREATE POLICY "Public Write ProductVariants" ON product_bulb_variants FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Write Sales" ON sales;
CREATE POLICY "Public Write Sales" ON sales FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Write Settings" ON store_settings;
CREATE POLICY "Public Write Settings" ON store_settings FOR ALL USING (true) WITH CHECK (true);

-- Admin Security Policies
DROP POLICY IF EXISTS "Super admins can manage admins" ON admins;
CREATE POLICY "Super admins can manage admins" ON admins FOR ALL USING (
  EXISTS (
    SELECT 1 FROM admins a
    WHERE a.email = (select auth.jwt() ->> 'email') 
    AND a.role = 'super_admin'
  )
);

DROP POLICY IF EXISTS "Allow Self Read" ON admins;
CREATE POLICY "Allow Self Read" ON admins FOR SELECT USING (true);
