-- =====================================================
-- COMPLETE SCHEMA DEPLOYMENT (SAFE SYNC) - V2
-- With Suppliers Support
-- =====================================================

-- 1. Create Lookup Tables
CREATE TABLE IF NOT EXISTS product_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text UNIQUE NOT NULL,
    description text
);

CREATE TABLE IF NOT EXISTS bulb_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    code text UNIQUE NOT NULL,
    description text
);

CREATE TABLE IF NOT EXISTS bulb_type_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    base_name text NOT NULL,
    variant_name text NOT NULL,
    display_name text NOT NULL,
    compatibility_list text[],
    description text,
    is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    contact_person text,
    email text,
    phone text,
    address text
);

-- 2. Create Products Table
CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    sku text UNIQUE,
    barcode text,
    brand text,
    category_id bigint REFERENCES product_categories(id),
    bulb_type_id bigint REFERENCES bulb_types(id),
    supplier_id bigint REFERENCES suppliers(id), -- Added relationship
    selling_price numeric(10,2) DEFAULT 0,
    cost_price numeric(10,2) DEFAULT 0,
    stock_quantity integer DEFAULT 0,
    min_stock_level integer DEFAULT 5,
    reorder_level integer DEFAULT 10,
    description text,
    image_url text,
    voltage numeric,
    wattage numeric,
    color_temperature text, 
    lumens numeric,
    beam_type text,
    specifications jsonb DEFAULT '{}'::jsonb,
    has_variants boolean DEFAULT false
);

-- 3. Create Product Bulb Variants Table (Junction)
CREATE TABLE IF NOT EXISTS product_bulb_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    product_id bigint REFERENCES products(id) ON DELETE CASCADE,
    variant_id bigint REFERENCES bulb_type_variants(id) ON DELETE RESTRICT,
    variant_sku text,
    variant_barcode text,
    variant_color text,
    price_adjustment numeric(10,2) DEFAULT 0,
    stock_quantity integer DEFAULT 0,
    is_primary boolean DEFAULT false,
    UNIQUE(product_id, variant_id)
);

-- 4. Enable RLS (Security) - Default to public access for this demo
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE bulb_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE bulb_type_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_bulb_variants ENABLE ROW LEVEL SECURITY;

-- Creating policies only if they don't exist is tricky in SQL multiple times
-- So we drop then create or just use DO blocks. For simplicity in raw SQL editor workflow:
DROP POLICY IF EXISTS "Public Access Categories" ON product_categories;
CREATE POLICY "Public Access Categories" ON product_categories FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Access BulbTypes" ON bulb_types;
CREATE POLICY "Public Access BulbTypes" ON bulb_types FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Access Variants" ON bulb_type_variants;
CREATE POLICY "Public Access Variants" ON bulb_type_variants FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Access Suppliers" ON suppliers;
CREATE POLICY "Public Access Suppliers" ON suppliers FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Access Products" ON products;
CREATE POLICY "Public Access Products" ON products FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Access ProductVariants" ON product_bulb_variants;
CREATE POLICY "Public Access ProductVariants" ON product_bulb_variants FOR ALL USING (true);

-- 5. Seed some initial Lookup Data if empty
INSERT INTO product_categories (name, description) VALUES
('Headlight', 'Main front lighting'),
('Fog Light', 'Auxiliary fog lights'),
('Signal Light', 'Turn signals'),
('Interior Light', 'Cabin lighting'),
('Brake Light', 'Rear brake lights')
ON CONFLICT (name) DO NOTHING;

INSERT INTO bulb_type_variants (base_name, variant_name, compatibility_list, display_name, description) VALUES
('LED Headlight Kit', 'H4/H7/9005/9006', ARRAY['H4', 'H7', '9005', '9006'], 'Universal Kit (H4/H7/9005/9006)', 'Universal fit for most cars'),
('LED Headlight Kit', 'H4/Hb2/9003', ARRAY['H4', 'Hb2', '9003'], 'Hi/Lo Beam (H4)', 'Standard high/low beam'),
('LED Headlight Kit', 'H7', ARRAY['H7'], 'Low Beam (H7)', 'Standard low beam'),
('LED Headlight Kit', '9005/HB3', ARRAY['9005', 'HB3'], 'High Beam (9005)', 'Standard high beam'),
('LED Headlight Kit', '9006/HB4', ARRAY['9006', 'HB4'], 'Low Beam (9006)', 'Standard low beam'),
('LED Fog Light', 'H11/H8/H16', ARRAY['H11', 'H8', 'H16'], 'Fog Universal (H11/H8/H16)', 'Universal fog light'),
('LED Signal', '1156/BA15S', ARRAY['1156', 'BA15S'], 'Single Contact (1156)', 'Turn signal / Reverse'),
('LED Signal', '7440/T20', ARRAY['7440', 'T20'], 'Wedge Base (7440)', 'Turn signal'),
('Interior LED', 'T10/194/168', ARRAY['T10', '194', '168'], 'Wedge T10 (Universal)', 'Parking/Interior/Plate'),
('Interior LED', 'Festoon 31mm', ARRAY['31mm'], 'Festoon 31mm', 'Dome light'),
('Interior LED', 'Festoon 36mm', ARRAY['36mm'], 'Festoon 36mm', 'Dome light')
ON CONFLICT DO NOTHING;

-- 6. Recreate the View
DROP VIEW IF EXISTS pos_product_variants;
CREATE OR REPLACE VIEW pos_product_variants AS
SELECT 
    p.id as product_id,
    p.sku,
    p.name as base_name,
    p.brand,
    p.selling_price as base_price,
    btv.id as variant_id,
    btv.display_name,
    btv.compatibility_list,
    btv.description as variant_description,
    p.selling_price + pbv.price_adjustment as final_price,
    pbv.stock_quantity,
    pbv.is_primary,
    pbv.variant_sku,
    pc.name as category,
    p.image_url,
    COALESCE(pbv.variant_color, CAST(p.color_temperature AS text)) as color_temperature
FROM products p
JOIN product_bulb_variants pbv ON p.id = pbv.product_id
JOIN bulb_type_variants btv ON pbv.variant_id = btv.id
LEFT JOIN product_categories pc ON p.category_id = pc.id
WHERE p.has_variants = true
  AND btv.is_active = true
ORDER BY p.name, btv.display_name;

-- 7. Sync Function
CREATE OR REPLACE FUNCTION sync_product_stock_from_variants()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE products
    SET stock_quantity = (
        SELECT COALESCE(SUM(stock_quantity), 0)
        FROM product_bulb_variants
        WHERE product_id = NEW.product_id
    )
    WHERE id = NEW.product_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8. Trigger for Sync
DROP TRIGGER IF EXISTS trigger_sync_product_stock ON product_bulb_variants;
CREATE TRIGGER trigger_sync_product_stock
AFTER INSERT OR UPDATE OR DELETE ON product_bulb_variants
FOR EACH ROW EXECUTE FUNCTION sync_product_stock_from_variants();

SELECT 'Full Schema V2 Deployed Successfully' as status;
