-- =====================================================
-- MASTER SCHEMA EXPORT
-- Use this script to replicate the Ken's Inventory POS schema
-- =====================================================

-- 1. DROP EXISTING (USE WITH CAUTION)
-- DROP VIEW IF EXISTS pos_product_variants;
-- DROP TABLE IF EXISTS sales;
-- DROP TABLE IF EXISTS product_bulb_variants;
-- DROP TABLE IF EXISTS products;
-- DROP TABLE IF EXISTS bulb_type_variants;
-- DROP TABLE IF EXISTS bulb_types;
-- DROP TABLE IF EXISTS product_categories;
-- DROP TABLE IF EXISTS suppliers;
-- DROP TABLE IF EXISTS store_settings;

-- 2. LOOKUP TABLES
CREATE TABLE IF NOT EXISTS product_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text UNIQUE NOT NULL,
    description text
);

CREATE TABLE IF NOT EXISTS bulb_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    code text UNIQUE NOT NULL,
    description text
);

CREATE TABLE IF NOT EXISTS bulb_type_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    base_name text NOT NULL,
    variant_name text NOT NULL,
    display_name text NOT NULL,
    compatibility_list text[],
    description text,
    is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    contact_person text,
    email text,
    phone text,
    address text
);

CREATE TABLE IF NOT EXISTS store_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name text DEFAULT 'Ken''s Auto Parts',
    tax_rate numeric DEFAULT 0.12,
    low_stock_threshold integer DEFAULT 5,
    currency text DEFAULT 'PHP',
    updated_at timestamp with time zone DEFAULT now()
);

-- 3. PRODUCTS & VARIANTS
CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    name text NOT NULL,
    sku text UNIQUE,
    barcode text,
    brand text,
    category_id bigint REFERENCES product_categories(id),
    bulb_type_id bigint REFERENCES bulb_types(id),
    supplier_id bigint REFERENCES suppliers(id),
    selling_price numeric(10,2) DEFAULT 0,
    cost_price numeric(10,2) DEFAULT 0,
    stock_quantity integer DEFAULT 0,
    min_stock_level integer DEFAULT 5,
    reorder_level integer DEFAULT 10,
    description text,
    image_url text,
    voltage numeric,
    wattage numeric,
    color_temperature text, 
    lumens numeric,
    beam_type text,
    specifications jsonb DEFAULT '{}'::jsonb,
    has_variants boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS product_bulb_variants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    product_id bigint REFERENCES products(id) ON DELETE CASCADE,
    variant_id bigint REFERENCES bulb_type_variants(id) ON DELETE RESTRICT,
    bulb_type text, -- Display type (e.g., H4, H11)
    color_temperature text, -- Display temp (e.g., 6000K)
    variant_sku text,
    variant_barcode text,
    selling_price numeric(10,2) DEFAULT 0,
    cost_price numeric(10,2) DEFAULT 0,
    stock_quantity integer DEFAULT 0,
    min_stock_level integer DEFAULT 5,
    is_primary boolean DEFAULT false,
    UNIQUE(product_id, bulb_type, color_temperature)
);

-- 4. SALES HISTORY
CREATE TABLE IF NOT EXISTS sales (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    items jsonb NOT NULL, -- Array of cart items
    subtotal numeric(10,2) NOT NULL,
    tax numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    payment_method text DEFAULT 'Cash',
    customer_name text,
    customer_email text,
    receipt_number text,
    transaction_status text DEFAULT 'completed',
    staff_id text,
    notes text
);

-- 5. VIEWS & FUNCTIONS
CREATE OR REPLACE VIEW pos_product_variants AS
SELECT 
    pbv.id as id,
    p.id as product_id,
    p.name as base_name,
    p.brand,
    pbv.bulb_type,
    pbv.color_temperature,
    pbv.selling_price,
    pbv.stock_quantity,
    pbv.min_stock_level,
    pbv.variant_sku,
    pc.name as category,
    p.image_url
FROM product_bulb_variants pbv
JOIN products p ON p.id = pbv.product_id
LEFT JOIN product_categories pc ON p.category_id = pc.id;

CREATE OR REPLACE FUNCTION sync_product_stock_from_variants()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE products
    SET stock_quantity = (
        SELECT COALESCE(SUM(stock_quantity), 0)
        FROM product_bulb_variants
        WHERE product_id = COALESCE(NEW.product_id, OLD.product_id)
    )
    WHERE id = COALESCE(NEW.product_id, OLD.product_id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_sync_product_stock ON product_bulb_variants;
CREATE TRIGGER trigger_sync_product_stock
AFTER INSERT OR UPDATE OR DELETE ON product_bulb_variants
FOR EACH ROW EXECUTE FUNCTION sync_product_stock_from_variants();

-- 6. RLS POLICIES (ENABLE PUBLIC READ/WRITE FOR DEMO)
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE bulb_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE bulb_type_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_bulb_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_settings ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    EXECUTE 'CREATE POLICY "Public Read" ON products FOR SELECT USING (true)';
    EXECUTE 'CREATE POLICY "Public Write" ON products FOR ALL USING (true) WITH CHECK (true)';
    -- Repeat for other tables if policies don't exist
EXCEPTION WHEN others THEN NULL;
END $$;

-- Simpler catch-all policies for rest of the tables
CREATE POLICY "Public Access" ON product_categories FOR ALL USING (true);
CREATE POLICY "Public Access" ON bulb_types FOR ALL USING (true);
CREATE POLICY "Public Access" ON bulb_type_variants FOR ALL USING (true);
CREATE POLICY "Public Access" ON suppliers FOR ALL USING (true);
CREATE POLICY "Public Access" ON product_bulb_variants FOR ALL USING (true);
CREATE POLICY "Public Access" ON sales FOR ALL USING (true);
CREATE POLICY "Public Access" ON store_settings FOR ALL USING (true);

-- 7. INITIAL SETTINGS
INSERT INTO store_settings (id, store_name, currency)
VALUES (1, 'Ken''s Auto Parts', 'PHP')
ON CONFLICT (id) DO UPDATE SET store_name = EXCLUDED.store_name;
