


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Admins" (
    "id" "uuid" NOT NULL,
    "email" "text",
    "role" "text" DEFAULT 'admin'::"text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."Admins" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Parts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying,
    "description" "text",
    "price" double precision,
    "quantity" bigint,
    "category" "text",
    "minQuantity" bigint,
    "sku" "text"
);


ALTER TABLE "public"."Parts" OWNER TO "postgres";


ALTER TABLE "public"."Parts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Engines_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "userName" character varying,
    "email" "text"
);


ALTER TABLE "public"."Users" OWNER TO "postgres";


COMMENT ON TABLE "public"."Users" IS 'for app users';



ALTER TABLE "public"."Users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."cars" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "carName" "text",
    "carBrand" "text",
    "carColor" "text",
    "quantity" bigint,
    "price" double precision
);


ALTER TABLE "public"."cars" OWNER TO "postgres";


ALTER TABLE "public"."cars" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cars_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."kv_store_9ac7f27f" (
    "key" "text" NOT NULL,
    "value" "jsonb" NOT NULL
);


ALTER TABLE "public"."kv_store_9ac7f27f" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."northwind" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."northwind" OWNER TO "postgres";


ALTER TABLE "public"."northwind" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."northwind_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sales" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "items" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "subtotal" numeric(12,2) NOT NULL,
    "tax" numeric(12,2) NOT NULL,
    "total" numeric(12,2) NOT NULL,
    "payment_method" "text" NOT NULL
);


ALTER TABLE "public"."sales" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."store_settings" (
    "id" bigint NOT NULL,
    "store_name" "text" DEFAULT 'KEN''S GARAGE'::"text",
    "tax_rate" numeric DEFAULT 8.25,
    "low_stock_threshold" integer DEFAULT 10,
    "currency" "text" DEFAULT 'USD'::"text",
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."store_settings" OWNER TO "postgres";


ALTER TABLE "public"."store_settings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."store_settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."suppliers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "contact_person" "text",
    "email" "text",
    "phone" "text",
    "address" "text",
    "category" "text"
);


ALTER TABLE "public"."suppliers" OWNER TO "postgres";


ALTER TABLE "public"."suppliers" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."suppliers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Admins"
    ADD CONSTRAINT "Admins_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Parts"
    ADD CONSTRAINT "Engines_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cars"
    ADD CONSTRAINT "cars_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."kv_store_9ac7f27f"
    ADD CONSTRAINT "kv_store_9ac7f27f_pkey" PRIMARY KEY ("key");



ALTER TABLE ONLY "public"."northwind"
    ADD CONSTRAINT "northwind_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."store_settings"
    ADD CONSTRAINT "store_settings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."suppliers"
    ADD CONSTRAINT "suppliers_pkey" PRIMARY KEY ("id");



CREATE INDEX "kv_store_9ac7f27f_key_idx" ON "public"."kv_store_9ac7f27f" USING "btree" ("key" "text_pattern_ops");



CREATE INDEX "kv_store_9ac7f27f_key_idx1" ON "public"."kv_store_9ac7f27f" USING "btree" ("key" "text_pattern_ops");



ALTER TABLE ONLY "public"."Admins"
    ADD CONSTRAINT "Admins_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE "public"."Admins" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable all access" ON "public"."sales" USING (true);



CREATE POLICY "Public can view admins" ON "public"."Admins" FOR SELECT TO "authenticated", "anon" USING (true);



ALTER TABLE "public"."kv_store_9ac7f27f" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."northwind" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."Admins" TO "anon";
GRANT ALL ON TABLE "public"."Admins" TO "authenticated";
GRANT ALL ON TABLE "public"."Admins" TO "service_role";



GRANT ALL ON TABLE "public"."Parts" TO "anon";
GRANT ALL ON TABLE "public"."Parts" TO "authenticated";
GRANT ALL ON TABLE "public"."Parts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Engines_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Engines_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Engines_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Users" TO "anon";
GRANT ALL ON TABLE "public"."Users" TO "authenticated";
GRANT ALL ON TABLE "public"."Users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."cars" TO "anon";
GRANT ALL ON TABLE "public"."cars" TO "authenticated";
GRANT ALL ON TABLE "public"."cars" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cars_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cars_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cars_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."kv_store_9ac7f27f" TO "anon";
GRANT ALL ON TABLE "public"."kv_store_9ac7f27f" TO "authenticated";
GRANT ALL ON TABLE "public"."kv_store_9ac7f27f" TO "service_role";



GRANT ALL ON TABLE "public"."northwind" TO "anon";
GRANT ALL ON TABLE "public"."northwind" TO "authenticated";
GRANT ALL ON TABLE "public"."northwind" TO "service_role";



GRANT ALL ON SEQUENCE "public"."northwind_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."northwind_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."northwind_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sales" TO "anon";
GRANT ALL ON TABLE "public"."sales" TO "authenticated";
GRANT ALL ON TABLE "public"."sales" TO "service_role";



GRANT ALL ON TABLE "public"."store_settings" TO "anon";
GRANT ALL ON TABLE "public"."store_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."store_settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."store_settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."store_settings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."store_settings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."suppliers" TO "anon";
GRANT ALL ON TABLE "public"."suppliers" TO "authenticated";
GRANT ALL ON TABLE "public"."suppliers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."suppliers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."suppliers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."suppliers_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

drop policy "Public can view admins" on "public"."Admins";


  create policy "Public can view admins"
  on "public"."Admins"
  as permissive
  for select
  to anon, authenticated
using (true);


