-- =================================================================================
-- PHASE 1: REFERENCE TABLES & FK BACKFILL
-- 
-- Description:
-- 1. Creates `brands` table and extracts unique brands from `products.brand`.
-- 2. Adds `brand_id` FK to `products` and backfills it.
-- 3. Adds `variant_category_id` FK to `product_variants` and backfills from `variant_type`.
-- 4. Adds `staff_uuid` to `sales` and backfills from `staff_id` string.
-- =================================================================================

-- --------------------------------------------------------
-- 1. Brands
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.brands (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  created_at  timestamptz DEFAULT now()
);

-- Enable RLS on brands
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read access to brands" ON public.brands
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow admin write access to brands" ON public.brands
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.admins WHERE admins.id = auth.uid() AND admins.is_active = true)
  );

-- Backfill distinct brands into the new table
INSERT INTO public.brands (name)
SELECT DISTINCT brand 
FROM public.products
WHERE brand IS NOT NULL AND brand != ''
ON CONFLICT (name) DO NOTHING;

-- Add FK column to products
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS brand_id bigint REFERENCES public.brands(id) ON DELETE SET NULL;

-- Link products to their new brand records
UPDATE public.products p 
SET brand_id = b.id 
FROM public.brands b 
WHERE p.brand = b.name;

-- --------------------------------------------------------
-- 2. Variant Types
-- --------------------------------------------------------
-- The free-text variant_type duplicates variant_categories. We'll add the FK directly.
ALTER TABLE public.product_variants 
ADD COLUMN IF NOT EXISTS variant_category_id bigint REFERENCES public.variant_categories(id) ON DELETE SET NULL;

-- Backfill matching variant_type text to variant_categories.code
UPDATE public.product_variants pv
SET variant_category_id = vc.id
FROM public.variant_categories vc
WHERE pv.variant_type = vc.code;

-- --------------------------------------------------------
-- 3. Sales Staff FK
-- --------------------------------------------------------
-- Staff ID in sales is currently text. Add a proper UUID FK to admins table.
ALTER TABLE public.sales 
ADD COLUMN IF NOT EXISTS staff_uuid uuid REFERENCES public.admins(id) ON DELETE SET NULL;

-- Backfill existing staff_id strings that are valid UUIDs
UPDATE public.sales 
SET staff_uuid = staff_id::uuid 
WHERE staff_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$';

