
-- Phase 1: Create category_metadata table for dynamic attribute system
CREATE TABLE IF NOT EXISTS category_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES product_categories(id) ON DELETE CASCADE,
    variant_type_label TEXT DEFAULT 'Type / Size',
    fields JSONB DEFAULT '[]'::jsonb,
    suggested_variant_types TEXT[] DEFAULT '{}',
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(category_id)
);

-- Enable RLS
ALTER TABLE category_metadata ENABLE ROW LEVEL SECURITY;

-- Dynamic Policies
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'category_metadata' AND policyname = 'Public Access'
    ) THEN
        CREATE POLICY "Public Access" ON category_metadata FOR ALL USING (true);
    END IF;
END $$;

-- Trigger for updated_at
CREATE OR REPLACE TRIGGER update_category_metadata_updated_at
    BEFORE UPDATE ON category_metadata
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
