-- =================================================================================
-- PHASE 2: SPECIFICATIONS EAV
-- 
-- Description:
-- 1. Create `product_specifications` and `variant_specifications` EAV tables.
-- 2. Backfill from hardcoded columns (voltage, wattage, etc.).
-- 3. Backfill from JSONB `specifications` blobs.
-- =================================================================================

-- --------------------------------------------------------
-- 1. Product Specifications EAV
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.product_specifications (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  spec_key    text NOT NULL,
  spec_value  text NOT NULL,
  created_at  timestamptz DEFAULT now(),
  UNIQUE (product_id, spec_key)
);

-- Enable RLS
ALTER TABLE public.product_specifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read access to product_specs" ON public.product_specifications
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow admin write access to product_specs" ON public.product_specifications
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.admins WHERE admins.id = auth.uid() AND admins.is_active = true)
  );

-- Backfill hardcoded product columns
INSERT INTO public.product_specifications (product_id, spec_key, spec_value)
SELECT id, 'voltage', voltage::text FROM public.products WHERE voltage IS NOT NULL
UNION ALL
SELECT id, 'wattage', wattage::text FROM public.products WHERE wattage IS NOT NULL
UNION ALL
SELECT id, 'lumens', lumens::text FROM public.products WHERE lumens IS NOT NULL
UNION ALL
SELECT id, 'color_temperature', color_temperature FROM public.products WHERE color_temperature IS NOT NULL
UNION ALL
SELECT id, 'beam_type', beam_type FROM public.products WHERE beam_type IS NOT NULL
ON CONFLICT (product_id, spec_key) DO NOTHING;

-- Backfill from JSONB specifications
INSERT INTO public.product_specifications (product_id, spec_key, spec_value)
SELECT p.id, kv.key, COALESCE(kv.value#>>'{}', '')
FROM public.products p, jsonb_each(p.specifications) AS kv
WHERE p.specifications IS NOT NULL AND p.specifications != '{}'::jsonb
ON CONFLICT (product_id, spec_key) DO NOTHING;

-- --------------------------------------------------------
-- 2. Variant Specifications EAV
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.variant_specifications (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id  bigint NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  spec_key    text NOT NULL,
  spec_value  text NOT NULL,
  created_at  timestamptz DEFAULT now(),
  UNIQUE (variant_id, spec_key)
);

-- Enable RLS
ALTER TABLE public.variant_specifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read access to variant_specs" ON public.variant_specifications
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow admin write access to variant_specs" ON public.variant_specifications
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.admins WHERE admins.id = auth.uid() AND admins.is_active = true)
  );

-- Backfill hardcoded variant columns
INSERT INTO public.variant_specifications (variant_id, spec_key, spec_value)
SELECT id, 'color_temperature', color_temperature FROM public.product_variants WHERE color_temperature IS NOT NULL
UNION ALL
SELECT id, 'variant_color', variant_color FROM public.product_variants WHERE variant_color IS NOT NULL
ON CONFLICT (variant_id, spec_key) DO NOTHING;

-- Backfill from JSONB variant specifications
INSERT INTO public.variant_specifications (variant_id, spec_key, spec_value)
SELECT pv.id, kv.key, COALESCE(kv.value#>>'{}', '')
FROM public.product_variants pv, jsonb_each(pv.specifications) AS kv
WHERE pv.specifications IS NOT NULL AND pv.specifications != '{}'::jsonb
ON CONFLICT (variant_id, spec_key) DO NOTHING;
;
